### ISSUE TITLE
Increase the number of build data saved in CI

### ISSUE THREAD

**Issue by augustocristian** [giis-uniovi/retorch-st-eShopContainers#43]
Currently, the CI system only retains data for the last 92 builds, accessible via the web API, ej.:
`https://URLJENKINS/job/retorch-st-fullteaching/job/main/api/json?tree=builds[number,result,timestamp]`
It is advisable to save the execution times and the pipeline state for a larger number of builds. Two alternatives are under consideration:
1. Archiving this data and timestamps as "artifacts" in an external system.
2. Increasing the parameter count in Jenkins (though this may result in storing data that is not useful exponentially).
What we should do @javiertuya ?

**Comment by augustocristian** [comment]
Some options to discuss: 

1. [Custom Step](https://medium.com/@sampark02/jenkins-how-to-retain-builds-forever-738172e44b52#:~:text=In%20Jenkins%2C%20you%20can%20retain,deleted%20to%20save%20disk%20space.)
2. [Using Jenkins Conf](https://stackoverflow.com/questions/57145735/how-to-change-the-number-of-builds-kept-by-jenkins)
3. External system composed by:
- [Logstash-Forwarder](https://github.com/elasticsearch/logstash-forwarder) for Collection & Transport
- [Logstash](http://logstash.net/) & [Riemann](http://riemann.io/) for Processing
- [ElasticSearch](http://www.elasticsearch.org/) for Storage & Queries
- [Kibana3](http://www.elasticsearch.org/overview/kibana/) for Visualisation

**Comment by javiertuya** [comment]
@augustocristian @ClaudiodelaRiva As far as I know, Jenkins does not limit the number of builds that are stored, provided that the branch is not deleted. This is the reason to user a build discarder plugin to purge old data. For deleted branches there is an optional orphaned retention strategy to retain additional info. 

Other different issue is whether the data can be viewed from an api without pagination control, in that case, is normal to get only the N more recent items where N is limited by the page size.

Therefore, I don't see anything that I can do for now.

Other very different thing, is if you are going to start experimenting with a large number of multiple runs. In this case, the best solution is what we talked about months ago: use an external system to keep the data. But this must be discussed in a meeting to determine whether we really need the best solution or something else.

**Comment by javiertuya** [comment]
As there are no other comments, I close the issue.
